name: linux-x64
on: [push, pull_request]

jobs:
  linux-gcc-x64:
    runs-on: ubuntu-20.04
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v4

    - name: build
      run: |
        mkdir build-ci && cd build-ci
        cmake ..
        cmake --build . -j 2
    - name: test
      run: |
        echo "pwd: `pwd`"
        cd build-ci
        # https://github.com/google/sanitizers/issues/723
        # https://github.com/google/sanitizers/issues/1322
        # https://github.com/google/sanitizers/issues/1321
        LSAN_OPTIONS=verbosity=1:log_threads=1 ASAN_OPTIONS=intercept_tls_get_addr=0 ctest --output-on-failure -j 2