name: linux-aarch64
on: [push, pull_request]

jobs:
  linux-gcc-aarch64:
    runs-on: ubuntu-20.04
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.12.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: cache-qemu
      id: cache-qemu
      uses: actions/cache@v3.3.1
      with:
        path: qemu-install
        key: qemu-aarch64-install-aarch64
    - name: checkout-qemu
      if: steps.cache-qemu.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: qemu/qemu
        path: qemu
        ref: f5643914a9e8f79c606a76e6a9d7ea82a3fc3e65
    - name: qemu
      if: steps.cache-qemu.outputs.cache-hit != 'true'
      run: |
        cd qemu
        ./configure --prefix=$GITHUB_WORKSPACE/qemu-install --target-list=aarch64-linux-user --disable-system
        make -j2
        make install

    - name: aarch64-gnu-toolchain
      run: |
        sudo apt-get update
        sudo apt-get install g++-aarch64-linux-gnu
    # - name: Cache APT Packages
    #   uses: awalsh128/cache-apt-pkgs-action@latest
    #   with:
    #     packages: g++-aarch64-linux-gnu
    #     version: 1.0

    - name: build
      run: |
        mkdir build-aarch64 && cd build-aarch64
        cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/aarch64-linux-gnu.toolchain.cmake ..
        cmake --build . -j 2
    - name: test
      run: |
        export PATH=$GITHUB_WORKSPACE/qemu-install/bin:$PATH
        echo "pwd: `pwd`"
        cd build-aarch64
        echo "pwd: `pwd`"
        echo "`which qemu-aarch64`"
        # https://github.com/google/sanitizers/issues/723
        # https://github.com/google/sanitizers/issues/1322
        # https://github.com/google/sanitizers/issues/1321
        ASAN_OPTIONS=detect_leaks=0 TESTS_EXECUTABLE_LOADER=qemu-aarch64 TESTS_EXECUTABLE_LOADER_ARGUMENTS="-L;/usr/aarch64-linux-gnu" ctest --output-on-failure -j 2
